version: '3'

services:
  web:
    image: ogalaemmanuel/devops-assignment:part2
    ports:
      - "3000:3000"
    networks:
      - webnet
    links:
      - redis-master
      - redis-slave
    depends_on:
      - redis-master
      - redis-slave
  redis-master:
    image: redis:4.0-alpine
    expose:
      - 6379
    entrypoint:
      - redis-server
      - --loglevel
      - verbose

  redis-slave:
    image: redis:4.0-alpine
    expose:
      - 6379
    entrypoint:
      - redis-server
      - --slaveof
      - redis-master
      - "6379"
      - --loglevel
      - verbose
networks:
  webnet:
